config/routes.rb
Sticky::Application.routes.draw do

<<<<<<< HEAD
  get '/notes/shared' => 'notes#shared'

  get '/notes/share' => 'notes#share'

  get 'notes/all' => 'notes#all'

  resources :shared_notes

  resources :contents

=======
  resources :contents

>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
  devise_for :users

  resources :notes

  root :to => 'home#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :note
  attr_accessible :description

  validates :description, :presence => true
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :name, :contents_attributes

  belongs_to :user
  has_many :contents

  accepts_nested_attributes_for :contents, :reject_if => lambda {|content| content[:description].blank? }, :allow_destroy => true

  validates :name, :presence => true
<<<<<<< HEAD

  def shared_to?(user)
    return true if self.user_id != user.id else false
  end

  def owner
    self.user.email
  end
=======
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
end

app/models/shared_note.rb
class SharedNote < ActiveRecord::Base
  # belongs_to :note
  belongs_to :user

  attr_accessor :email
  attr_accessible :email, :note_id
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
<<<<<<< HEAD
  has_many :shared_notes
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def self.shareable_to?(recipient, note_id)
    recipient_id = User.find_by_email(recipient).id
    if SharedNote.where("user_id = ? AND note_id = ?", "#{recipient_id}", "#{note_id}").empty?
      return true
    else
      return false
    end
  end

  def all_notes
    notes = self.notes.map {|n| n.id}
    shared = self.shared_notes.map {|s| s.note_id}

    @notes = []

    for note in notes
      @notes.push Note.find(note)
    end
    for shared_note in shared
      @notes.push Note.find(shared_note)
    end
    @notes
  end
=======
  attr_accessible :email, :password, :password_confirmation, :remember_me
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @notes = current_user.notes
      render 'notes/index'
    else
      render 'home/index'
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :find_note, :only => [:show, :edit, :update, :destroy]
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes}
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
<<<<<<< HEAD
      format.json { render json: {:note => @note, :contents => @note.contents, :shared => @note.shared_to?(current_user), :owner => @note.owner} }
=======
      format.json { render json: @note, :include => :contents}
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = current_user.notes.new
    @content = @note.contents.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    render 'notes/edit', layout: false
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to root_path, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to root_path, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Successfully deleted note." }
      format.json { head :no_content }
    end
  end

<<<<<<< HEAD
  def share
    @shared_note = SharedNote.new
    render json: {:form => render_to_string(:partial => "notes/share")}
  end

  def shared
    shared = SharedNote.find(:all, :conditions => {:user_id => current_user.id}).collect {|s| s.note_id }
    if shared.blank?
      @notes = []
    else
      #@notes = Note.where("id IN (?)", "#{shared.join(',')}")
      @notes = Note.where(:id => shared)
    end
  end

  def all
    @notes = current_user.all_notes
  end

  private
    def find_note
      @note = Note.find(params[:id])
=======
  private
    def find_note
      @note = current_user.notes.find(params[:id])
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
    end
end

app/controllers/shared_notes_controller.rb
class SharedNotesController < ApplicationController

  def create

    if params[:email] == current_user.email
      render json: {:status => "error", :error_description => "You can't share note to self."}
    elsif User.find_by_email(params[:email]).blank?
      render json: {:status => "error", :error_description => "The email address does not exist."}
    else
      if User.shareable_to?(params[:email], params[:shared_note][:note_id])
        @user = User.find_by_email(params[:email])
        @shared_note = @user.shared_notes.build(params[:shared_note])
        if @shared_note.save
          @note = current_user.notes.find(@shared_note.note_id)
          render json: {:status => "success", :note => @note}
        else
          render json: {:status => "error", :error_description => "The note could not be shared."}
        end
      else
        render json: {:status => "error", :error_description => "The note is already shared to #{params[:email]}."}
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.shareable_to(current_user)
    
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_content_header.html.haml
.row-fluid
  .span8.offset2
    %h1.pagination-centered Network Stickies!
- unless user_signed_in?
  .row-fluid
    .span8.offset2
      .well.pagination-centered
        Network Stickies is your handy online sticky note app, when all else is there.

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%button.btn.btn-navbar{:type => "button", "data-toggle" => "collapse", "data-target" => ".nav-collapse"}
  - 3.times do
    %span.icon-bar
= link_to "Home", root_path, :class => 'brand'
.nav-collapse.collapse.pull-right
  %ul.nav
    - if user_signed_in?
      %li
<<<<<<< HEAD
        = link_to "Welcome #{current_user.email}!", "#"
      %li
=======
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
        = link_to('Account', edit_user_registration_path)
      %li
        = link_to('Logout', destroy_user_session_path, :method=>'delete')
    - else
      %li
        = link_to('Login', new_user_session_path)
      %li
        = link_to('Sign up', new_user_registration_path)

app/views/layouts/_sidebar.html.haml
.well
  %ul.pagination-centered{:style => "list-style: none; margin-left: 0 !important;"}
    %li
      = link_to "My Notes", root_path, :class => "btn", :style => "min-width: 80%; margin: 8px auto"
    %li 
<<<<<<< HEAD
      = link_to "Shared", notes_shared_path, :class => "btn", :style => "min-width: 80%; margin: 8px auto"
    %li 
      = link_to "All Notes", notes_all_path, :class => "btn", :style => "min-width: 80%; margin: 8px auto"
=======
      = link_to "Shared", "javascript:void(0);", :class => "btn", :style => "min-width: 80%; margin: 8px auto"
    %li 
      = link_to "All Notes", "javascript:void(0);", :class => "btn", :style => "min-width: 80%; margin: 8px auto"
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Network Stickies"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row-fluid
            .span12
              = render 'layouts/messages'
              = render 'layouts/content_header'
              - if user_signed_in?
                .row-fluid
                  .span3
                    = render 'layouts/sidebar'
                  .span9
                    = yield
              - else
                .span12
                  = yield
          %footer

app/views/notes/_form.html.haml
= simple_nested_form_for(@note) do |f|
  - if @note.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  = f.fields_for :contents do |c|
    = c.input :description
    = c.link_to_remove "Remove Content"
  = f.link_to_add "Add New Content", :contents
  .actions
    = f.submit

app/views/notes/_modal.html.haml
#noteModal.modal.hide.fade
  .modal-header
    %button.close{:type => "button", :data => {:dismiss => "modal"}, :aria => {:hidden => "true"}} &times;
<<<<<<< HEAD
    %h3
      %span.note-title
      = link_to "Share Note", "#", :class => 'btn btn-share', :onclick => "shareNote();"
  .modal-body
    %p
=======
    %h3 Modal header
  .modal-body
    %p note contents
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
  .modal-footer

app/views/notes/_note.html.haml
.span4.notes
  .well
    %strong= note.name
<<<<<<< HEAD
    %br/
    %em= "by #{note.user.email}"
=======
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
    .clearfix
    .btn-group.pull-right
      = link_to "#noteModal", :class => "btn btn-mini btn-shownote", :role => "button", :data => {:toggle => "modal", :id => note.id} do
        %i.icon-zoom-in
<<<<<<< HEAD
      - if note.user == current_user
        = link_to "#noteModal", :class => "btn btn-mini btn-editnote", :role => "button", :data => {:toggle => "modal", :id => note.id} do
          %i.icon-edit
        = link_to note_path(note), :class => "btn btn-mini", :data => {:confirm => "Are you sure?"}, :method => :delete do
          %i.icon-trash
    .clearfix
    %br/
    - if note.user != current_user
      %em.label.pull-right= "by #{note.user.email}"
=======
      = link_to "#noteModal", :class => "btn btn-mini btn-editnote", :role => "button", :data => {:toggle => "modal", :id => note.id} do
        %i.icon-edit
      = link_to note_path(note), :class => "btn btn-mini", :data => {:confirm => "Are you sure?"}, :method => :delete do
        %i.icon-trash
>>>>>>> 36a2f3959683644bcb532aad8e692ce805cf3d76
    .clearfix

app/views/notes/_share.html.haml
= simple_fields_for @shared_note do |f|
  = f.input :email, label: "Share this note via email address"
  = link_to "Share", "javascript:void(0);", :class => "btn btn-success", :onclick => "createSharedNote();"

app/views/notes/all.html.haml
%h3 Available Notes
%hr/
.row-fluid
  - if @notes.empty?
    .span8.offset2.notes.pagination-centered
      .well
        %strong No notes have been shared to you.
  - else
    - for note in @notes
      = render 'notes/note', :note => note

= render 'notes/modal'

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.haml
%h3 My Notes
%hr/
.row-fluid
  .span12.pagination-centered
    = link_to new_note_path do
      %button.btn Add Note
%br/
.row-fluid
  - for note in @notes
    = render 'notes/note', :note => note
  - unless @notes.empty?
    .span4.notes.pagination-centered
      .well
        = link_to new_note_path do
          %button.btn Add Note
= render 'notes/modal'

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/shared.html.haml
%h3 Shared Notes
%hr/
.row-fluid
  - if @notes.empty?
    .span8.offset2.notes.pagination-centered
      .well
        %strong No notes have been shared to you.
  - else
    - for note in @notes
      = render 'notes/note', :note => note

= render 'notes/modal'

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @note.name %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>